name: Create Pull Request and Automerge

on:
  push:
    branches:
      - main

jobs:
  create-pr-and-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git config --global credential.helper store

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create a Pull Request
        run: |
          response=$(curl -s -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -X POST \
            -d '{
              "title": "Automated PR",
              "head": "my-test-branch",
              "base": "main",
              "body": "This PR was created automatically by GitHub Actions"
            }' \
            https://api.github.com/repos/mayezra/remote-repo/pulls)

          PR_NUMBER=$(echo "$response" | jq -r '.number')
          echo "Pull request created: $PR_NUMBER"

      - name: Merge PR to main
        if: success()
        run: |
          # Merge PR to main branch
          git fetch origin pull/$PR_NUMBER/head:pr-$PR_NUMBER
          git checkout main
          git merge --no-ff --no-edit pr-$PR_NUMBER
          git push origin main
